### PR TITLE
Bump Tor versions in the CI

### PR DESCRIPTION
**Pull request by robgjansen**

### CODE REVIEW

**Comment by robgjansen** [comment]
In the Tor 0.4.6.5 test that failed, there are 10 packet objects (and 10 payload objects) that did not get `free()`d. So the test fails due to a memory leak detected.

**Comment by stevenengler** [comment]
The tor commit that breaks shadow is torproject/tor@2444629c.

**Comment by stevenengler** [comment]
The packet leak issue was solved, but was found to be different from this issue.

This issue is at #1503.

**Comment by stevenengler** [comment]
@robgjansen Could you rebase this, I think it's ready to merge.

**Review by stevenengler — APPROVED** [review]

**Pull request merged**
