### PR TITLE
Made Elf Loader executable by python2 and python3

### PR DESCRIPTION
**Pull request by florian-vuillemot**

### CODE REVIEW

**Comment by robgjansen** [comment]
@jtracey would you be able to look this over to see if you notice any issues related to elf-loader?

**Comment by jtracey** [comment]
Of the files modified, `extract-system-config.py` is the only one used during regular Shadow builds. The changes to that file are minor. The other files changed are for the junit test framework, which we don't use any more, and for generating builds to run valgrind on elf-loader, which we're unlikely to need again. The edits to those files also look fine (I don't like the definition of `to_str()` in the junit definition, but since we won't be using this anyway, it doesn't really matter).

**Comment by florian-vuillemot** [comment]
I don't like the ```to_str()``` too, it's really dirty...
Maybe I should directly remove files that we will not use anymore ?

**Comment by robgjansen** [comment]
No need to remove `to_str`. I reviewed the branch and think it's fine.

The only thing is, we usually rebase onto master rather than merging master into the feature branch (i.e., you can't push that "update branch" button on Github). You would do this by making sure your master branch is up to date, and then while on commit 6a094247b9b9c8106850f385894623c0a1c35e15 run a rebase against master:

```
git checkout master
git pull
git checkout -b elfloader/python2to3-rebase 6a094247b9b9c8106850f385894623c0a1c35e15
git rebase master
git push --force  elfloader/python2to3-rebase:elfloader/python2to3
```

@florian-vuillemot do you want to give it a try to get more familiar with the process? Otherwise I can merge a rebased version of your changes in a separate PR. Let me know.

**Comment by florian-vuillemot** [comment]
I have to admit that I'm not used to rebase, I always merge ^^
Never mind, I tried ! I didn't merge on my machine so I just rebased localy and pushed. Looks nice but let me know if I made a mistake.
Sorry for making the same mistake twice.

**Comment by florian-vuillemot** [comment]
Hum, tests have failed. I will check asap. Don't hesitate to merge over PR, I will rebase :)

**Comment by robgjansen** [comment]
Thanks for rebasing! It looks like the tests are passing now :)

**Pull request merged**
