### PR TITLE
Change many function signatures from "C" to "C-unwind"

### PR DESCRIPTION
**Pull request by stevenengler**
I don't completely understand when to use "C" vs "C-unwind", but it sounds like the "C-unwind" will be the future-proof version of the current "C" behaviour.

From what I understand, function signatures should use "C-unwind" if they may unwind. Most of our exported rust functions should be "C-unwind" since they may panic. Our exported C functions should also be "C-unwind" since they may call C++ or rust functions that may throw an exception or panic. The linux-api code was left as "C" and not "C-unwind".

I'm not sure that this is correct everywhere, but hopefully is an improvement.

See #3151.

### CODE REVIEW

**Comment by stevenengler** [comment]
@sporksmith A ping in case you have any objections.

**Review by robgjansen — APPROVED** [review]

**Comment by sporksmith** [comment]
Thanks - no objection :)

> The linux-api code was left as "C" and not "C-unwind".

Any particular reason? I suppose it's relatively easy there to verify that those functions don't panic?

**Comment by stevenengler** [comment]
> Thanks - no objection :)
> 
> > The linux-api code was left as "C" and not "C-unwind".
> 
> Any particular reason? I suppose it's relatively easy there to verify that those functions don't panic?

I'm not really sure what we should use, but my thinking was that since these functions/structs are for the kernel interface, they probably shouldn't be functions that unwind. For example a signal handler probably shouldn't unwind, so I think `linux_api::signal::SignalHandlerFn` should be `extern "C" fn(i32)` rather than `extern "C-unwind" fn(i32)`.

I should clarify that I did change the rust functions we export to C, for example I changed:

```diff
-    pub extern "C" fn linux_sigemptyset() -> linux_sigset_t {
+    pub extern "C-unwind" fn linux_sigemptyset() -> linux_sigset_t {
```

but things like `linux_api::signal::SignalHandlerFn` and `pub unsafe extern "C" fn sigaction_restorer()` were left as "C" and not "C-unwind".

**Comment by sporksmith** [comment]
> I should clarify that I did change the rust functions we export to C, for example I changed:

Ah ok, yeah that makes sense

**Pull request merged**
