### PR TITLE
Fix pthread test bugs

### PR DESCRIPTION
**Pull request by florian-vuillemot**
Allow to run the pthread test with one or more then 6 threads

### CODE REVIEW

**Comment by florian-vuillemot** [comment]
If I understand correctly this error doesn't come from my code but from the openssl dependancy that moved from https://www.openssl.org/source/openssl-1.0.1e.tar.gz to https://openssl.org/source/old/1.0.1/openssl-1.0.1.tar.gz in the shadow-plugin-tor .
Issue: https://github.com/shadow/shadow-plugin-tor/issues/92

**Comment by sporksmith** [comment]
I have #754 out to fix the integration test.

**Comment by florian-vuillemot** [comment]
I'm not quite sure about what I have just done ! I think I started by making a mistake right before doing what you suggested @robgjansen 
Is it correct now?

**Comment by robgjansen** [comment]
@florian-vuillemot I think this looks OK. Thank you!

**Pull request merged**
