### PR TITLE
Backport Centos 7 fixes

### LINKED ISSUE #850: Missing stdint stuff on CentOS 7
**Describe the issue**

```
In file included from /scratch/mtraudt/shadow/src/main/host/descriptor/tcp_retransmit_tally.cc:1:0:
/scratch/mtraudt/shadow/src/main/host/descriptor/tcp_retransmit_tally.h:3:30: fatal error: bits/stdint-intn.h: No such file or directory
 #include <bits/stdint-intn.h>
```

**To Reproduce**
Steps to reproduce the behavior. If you problem involves a simulation, please include the configuration file that you used.

```
./setup build
```

**Operating System (please complete the following information):**

CentOS Linux release 7.6.1810 (Core)

Linux koios1.chacs.nrl.navy.mil 4.4.180-2.el7.elrepo.x86_64 #1 SMP Wed May 22 08:01:41 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Shadow (please complete the following information):**

Doesn't compile, but HEAD is 9f7cd4131876f5a6df0b851b15dbe3180210bfec

 - Which plug-ins you are using:  N/A

**Additional context**

1d61d4bed7ede64ee006ad49cc17335705dcd0e9 seems to be the offending commit. At least, it's the one that last touched the `#include` lines with `bits/`.

### PR DESCRIPTION
**Pull request by sporksmith**
fixes #850

### CODE REVIEW

**Comment by sporksmith** [comment]
@pastly could you test this on Centos 7?

**Comment by stevenengler** [comment]
This PR plus the patch [here](https://paste.debian.net/hidden/2d41688f/) is enough for it to build and pass all the tests on CentOS 7.

**Comment by pastly** [comment]
On the todo list for Monday.

**Comment by sporksmith** [comment]
@stevenengler your patch didn't apply for me. Spot-checking, it looks like these changes were already made in c0e9090c6e95c61242a02cbf9003f3220de28261 (one of the backported commits)

**Comment by stevenengler** [comment]
@sporksmith Oops :/ It looks like I cloned your repository but forgot to checkout the branch. I assumed any changes I needed were just for files in shadow but not in phantom. This PR builds okay as-is for me on CentOS 7.

**Comment by sporksmith** [comment]
@stevenengler cool, thanks for verifying!

**Comment by pastly** [comment]
Since I said I would: I can confirm that this branch by itself (*not* with the additional patch) builds for me on Centos 7.

**Pull request merged**
