### PR TITLE
Have Shadow tell the plugin not to spin when its blocked.

### LINKED ISSUE #965: Signal plugin when Shadow will block on a syscall
Currently in preload mode, the plugin makes a syscall and then spins until shadow gives it an answer. But sometimes Shadow needs to block before the ssycall can be completed, for example when it is waiting for a packet to read data. In this case, Shadow should send a message back to the plugin to inform it that we will be blocking it. This can be used as a signal so the plugin can stop spinning and instead do a `semaphore_wait()` call.

This strategy could allow us to avoid implementing an algorithm to dynamically compute the "optimal" spin time (as requested in #894), because we could just always spin until we get a response from Shadow.

### PR DESCRIPTION
**Pull request by sporksmith**
Fixes #965

I don't have conclusive evidence of this PR helping; and it might actually hurt. I don't understand why, though.

### CODE REVIEW

**Comment by sporksmith** [comment]
In my local tests this seems to have little effect in most circumstances, and sometimes make performance worse.

On my 4-core machine (8 with hyperthreading), with this PR:
```
$ sudo ci/run.sh -io 'centos:7;gcc;release'
...
$ sudo docker run -it shadow:centos-7-gcc-release ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=60
2020-09-14 15:38:13,487 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=60'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed    0.40 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed    0.25 sec
```

And at dev:
```
$ sudo ci/run.sh -io 'centos:7;gcc;release'
...
$ sudo docker run -it shadow:centos-7-gcc-release ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=60
$ sudo docker run -it shadow:centos-7-gcc-release ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=60
2020-09-14 15:41:39,093 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=60'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed    0.39 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed    0.22 sec
```

**Comment by sporksmith** [comment]
Patching to bump sim time from 3 to 60s (to amortize startup time), and only using 1 core (to increase core contention):

this PR:
```
$ sudo docker run --cpus=1 -it shadow:centos-7-gcc-release ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=60
2020-09-14 15:55:35,298 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=60'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed   24.64 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed   27.17 sec
```

at dev:
```
$ sudo docker run --cpus=1 -it shadow:centos-7-gcc-release ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=60
2020-09-14 15:51:24,306 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=60'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed   56.32 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed   29.89 sec
```

While it doesn't help in the threaded benchmark (2 workers), it does seem to help in phold-shadow-preload, which only uses 1 worker (56s -> 25s). I'm not sure why this'd be more helpful in that case, since there's less CPU contention.

Actually it's surprising that the threaded version is faster at all than the non-threaded version @dev and given only 1 CPU core. The only way I could imagine it helping is if shadow itself ends up making blocking syscalls in the hot path, in which case the 2nd worker thread could get swapped in while the 1st is blocked. I don't think that should be happening, though.

**Comment by sporksmith** [comment]
I don't fully understand how the --cpus flag in docker is implemented. Rather than trying to restrict to 1 core, increased the number of workers to 8. Surprisingly this PR seems to make performance worse in the 8-worker case.

this PR:
```
$ sudo docker run -it shadow:centos-7-gcc-release ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=60
2020-09-14 16:25:53,194 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=60'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed   11.65 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed    6.63 sec
```

dev:
```
$ sudo docker run -it shadow:centos-7-gcc-release ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=60
2020-09-14 16:29:30,125 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=60'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed   11.95 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed    5.06 sec
```

**Comment by sporksmith** [comment]
Disabled this optimization by default. Can be enabled by setting environment variable SHADOW_EXPERIMENTAL_EXPLICIT_BLOCK (to anything).

Running again on my first 2 cores:

disabled (2 runs):
```
$ sudo docker run  -it shadow:centos-7-gcc-release taskset 0x00000003 ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=600
2020-09-14 19:22:46,526 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=600'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed    2.33 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed   10.28 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =  12.62 sec
2020-09-14 19:22:59,158 [INFO] ['ctest', '--output-on-failure', '-j1', '--timeout', '20', '-R', 'phold.*preload', '-C', 'ilibc', '--timeout=600'] returned 0
jnewsome@vusiri:~/projects/shadow$ sudo docker run  -it shadow:centos-7-gcc-release taskset 0x00000003 ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=600
2020-09-14 19:27:49,530 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=600'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed    1.82 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed   11.27 sec
```

enabled (2 runs):
```
$ sudo docker run -eSHADOW_EXPERIMENTAL_EXPLICIT_BLOCK=1 -it shadow:centos-7-gcc-release taskset 0x00000003 ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=600
2020-09-14 19:28:50,678 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=600'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed    0.47 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed    8.64 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =   9.12 sec
2020-09-14 19:28:59,804 [INFO] ['ctest', '--output-on-failure', '-j1', '--timeout', '20', '-R', 'phold.*preload', '-C', 'ilibc', '--timeout=600'] returned 0
jnewsome@vusiri:~/projects/shadow$ sudo docker run -eSHADOW_EXPERIMENTAL_EXPLICIT_BLOCK=1 -it shadow:centos-7-gcc-release taskset 0x00000003 ./setup test -j1 'phold.*preload' -- -C ilibc --timeout=600
2020-09-14 19:29:05,692 [INFO] calling 'ctest --output-on-failure -j1 --timeout 20 -R phold.*preload -C ilibc --timeout=600'
Test project /root/shadow/build
    Start 31: phold-shadow-preload
1/2 Test #31: phold-shadow-preload .............   Passed    0.48 sec
    Start 33: phold-threaded-shadow-preload
2/2 Test #33: phold-threaded-shadow-preload ....   Passed   11.30 sec
```

It might be helping in this core-starved case after all; in both modes there's quite a bit of fluctuation here. Perhaps that's to be expected given the interactions with the Linux scheduler and not running these on a dedicated machine.

@RWails when your benchmark matrix script is ready could you evaluate this? I don't have a strong opinion on whether to merge it in the meantime; it should be a no-op without SHADOW_EXPERIMENTAL_EXPLICIT_BLOCK set.

**Review by rwails — APPROVED** [review]
Looks good! I've also A/B tested this and noticed a slight improvement in performance for experiments with many hosts. It's easy to toggle this option so I think we should merge this 👍

**Pull request merged**
