### PR TITLE
Adding a test case for raw socket support.

### PR DESCRIPTION
**Pull request by lamiaaMB**

### CODE REVIEW

**Comment by robgjansen** [comment]
Also, after everything builds correctly, you should run `./setup test` to verify that your normal test case (`raw-socket`) passes, but the shadow test case (`rawsock-shadow`) fails.

**Comment by lamiaaMB** [comment]
Hello Rob,
I ran ./setup build and after "./setup install"  only one test case failed

>  ./setup test
2018-01-15 12:48:44,637 [INFO] calling 'ctest -j4'
Test project /home/lamiaa/files_to_backup/pull_req/shadow/build/src/external/elf-loader
      Start  1: elfloader-internals
      Start  2: elfloader-test0
      Start  3: elfloader-test0_1
      Start  4: elfloader-test0_2
 1/33 Test  #3: elfloader-test0_1 ................   Passed    0.01 sec
 2/33 Test  #2: elfloader-test0 ..................   Passed    0.11 sec
 3/33 Test  #4: elfloader-test0_2 ................   Passed    0.11 sec
      Start  5: elfloader-test1
      Start  6: elfloader-test2
      Start  7: elfloader-test3
 4/33 Test  #5: elfloader-test1 ..................   Passed    0.01 sec
 5/33 Test  #6: elfloader-test2 ..................   Passed    0.11 sec
 6/33 Test  #7: elfloader-test3 ..................   Passed    0.11 sec
      Start  8: elfloader-test4
      Start  9: elfloader-test5
      Start 10: elfloader-test6
 7/33 Test  #9: elfloader-test5 ..................   Passed    0.01 sec
 8/33 Test #10: elfloader-test6 ..................   Passed    0.11 sec
 9/33 Test  #8: elfloader-test4 ..................   Passed    0.11 sec
      Start 11: elfloader-test7
      Start 12: elfloader-test8
      Start 13: elfloader-test8_5
10/33 Test #11: elfloader-test7 ..................   Passed    0.01 sec
11/33 Test  #1: elfloader-internals ..............   Passed    0.43 sec
12/33 Test #12: elfloader-test8 ..................   Passed    0.10 sec
13/33 Test #13: elfloader-test8_5 ................   Passed    0.10 sec
      Start 14: elfloader-test9
      Start 15: elfloader-test10
      Start 16: elfloader-test11
      Start 17: elfloader-test12
14/33 Test #15: elfloader-test10 .................   Passed    0.01 sec
15/33 Test #14: elfloader-test9 ..................   Passed    0.01 sec
16/33 Test #16: elfloader-test11 .................   Passed    0.01 sec
17/33 Test #17: elfloader-test12 .................   Passed    0.02 sec
      Start 18: elfloader-test13
      Start 19: elfloader-test14
      Start 21: elfloader-test16
      Start 22: elfloader-test17
18/33 Test #22: elfloader-test17 .................   Passed    0.01 sec
19/33 Test #18: elfloader-test13 .................   Passed    0.01 sec
20/33 Test #21: elfloader-test16 .................   Passed    0.01 sec
21/33 Test #19: elfloader-test14 .................   Passed    0.01 sec
      Start 20: elfloader-test15
22/33 Test #20: elfloader-test15 .................   Passed    0.01 sec
      Start 23: elfloader-test18
      Start 24: elfloader-test19
      Start 25: elfloader-test20
      Start 26: elfloader-test21
23/33 Test #26: elfloader-test21 .................   Passed    0.01 sec
24/33 Test #25: elfloader-test20 .................   Passed    0.01 sec
25/33 Test #23: elfloader-test18 .................   Passed    0.01 sec
26/33 Test #24: elfloader-test19 .................   Passed    0.01 sec
      Start 27: elfloader-test22
      Start 28: elfloader-test23
      Start 29: elfloader-test24
      Start 30: elfloader-test25
27/33 Test #27: elfloader-test22 .................   Passed    0.01 sec
28/33 Test #29: elfloader-test24 .................   Passed    0.01 sec
29/33 Test #28: elfloader-test23 .................   Passed    0.01 sec
30/33 Test #30: elfloader-test25 .................   Passed    0.01 sec
      Start 31: elfloader-test26
      Start 32: elfloader-test27
      Start 33: elfloader-test28
31/33 Test #32: elfloader-test27 .................   Passed    0.01 sec
32/33 Test #31: elfloader-test26 .................***Failed    0.01 sec
33/33 Test #33: elfloader-test28 .................   Passed    0.61 sec

97% tests passed, 1 tests failed out of 33

Total Test time (real) =   1.11 sec

The following tests FAILED:
	 31 - elfloader-test26 (Failed)
Errors while running CTest
2018-01-15 12:48:45,788 [INFO] ctest -j4 returned 8
2018-01-15 12:48:45,788 [WARNING] Failed to pass all test cases!

**Comment by jtracey** [comment]
@lamiaaMB that's an elf-loader test, because it failed none of the shadow tests ran. test26 isn't that important yet, so you can just comment it out here: https://github.com/shadow/shadow/blob/077aef6923025e61a1ce465d90ee090d39a8b6da/src/external/elf-loader/test/CMakeLists.txt#L207

I'll take a closer look at what's going on with that test in the meantime, in #371.

**Comment by lamiaaMB** [comment]
Thank you for the response, I fixed that and the test results are like this now : 

>  Test #38: random-shadow ............................   Passed    0.10 sec
36/66 Test #32: phold-threaded-shadow ....................   Passed    1.72 sec
      Start 39: rawsock
      Start 40: rawsock-shadow
37/66 Test #40: rawsock-shadow ...........................***Exception: Other  0.20 sec
38/66 Test #39: rawsock ..................................   Passed    0.20 sec
      Start 41: signal

**Comment by robgjansen** [comment]
@lamiaaMB thanks. I assume you have made some edits to the code in order to compile and run this correctly (in order to fix the errors in my message above). Is this correct?

If so, could you please commit your latest code and push it to this pull request? I think you can add more commits by pushing to the `master` branch on `lamiaaMB/shadow`.

**Comment by lamiaaMB** [comment]
I've pushed the changes to lamiaaMB/shadow

**Comment by robgjansen** [comment]
Thanks for the effort!

Hmm... It still didn't build for me. I had to make several more changes to your code. There were some errors, for example passing an `int` when you should have been passing an `int*`.

I fixed them in my local branch.

The bigger issue, I think, is that this test case isn't really testing packet transfer between a client and a server. It only tests `socket` creation, `bind`, and a `setsockopt` on `PACKET_QDISC_BYPASS` (which actually is not supported on all systems including Cent OS 7). I'm worried that if we don't test packet transfer, and I go and implement raw sockets in Shadow, it won't actually work correctly and you will run into problems later when trying to run Tor.

I can try to fix these issues, and then do the shadow implementation, but please be aware that my time is limited so I can't give you a good estimate for how long it might take me.

**Comment by lamiaaMB** [comment]
Ok, since it might take a bit longer than I expected, I will add the data transfer test.  
Thank you so much Rob for your support

**Pull request closed without merging**
